language: node_js
node_js:
  - '8'
  - '6'

sudo: false
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

after_success: npm run coveralls
